### PR TITLE
fix: Handle patching XAPK files

### LINKED ISSUE #86: bug: Cannot patch XAPK files
### Bug description

XAPK files fail to patch

Example app (patch with "Disable play store updates")
https://apkpure.com/ru/strava-run-hike-android-exercise-laugh/com.strava/download

### Error logs

```shell
INFO: Loading patches 
INFO: Reading options from options.json 
SEVERE: An unexpected error occurred: Cannot invoke "com.reandroid.arsc.chunk.xml.AndroidManifestBlock.getPackageName()" because "manifest" is null 
java.lang.NullPointerException: Cannot invoke "com.reandroid.arsc.chunk.xml.AndroidManifestBlock.getPackageName()" because "manifest" is null
	at app.morphe.patcher.resource.coder.ArsclibResourceCoder.lazyPackageInfo$lambda$9(ArsclibResourceCoder.kt:124)
```

### Solution

_No response_

### Additional context

_No response_

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.

### PR DESCRIPTION
**Pull request by prateek-who**
The problem was cli was hard checking to only match apkm. Any other format would fall into the else branch and be considered as an apk. Now it checks for apkm and xapk.

### CODE REVIEW

File: src/main/kotlin/app/morphe/cli/command/PatchCommand.kt [hunk 1]
```diff
@@ -431,9 +431,11 @@ internal object PatchCommand : Callable<Int> {
 
             val patcherTemporaryFilesPath = temporaryFilesPath.resolve("patcher")
 
-            // Checking if the file is in apkm format (like reddit)
-            val inputApk = if (apk.extension.equals("apkm", ignoreCase = true)) {
-                logger.info("Merging APKM bundle")
+            // We need to check for both apkm (like reddit) and xapk formats here
+
+            val inputApk = if (apk.extension.lowercase() in  setOf("apkm", "xapk")) {
```
Comment (LisoUseInAIKyrios) [inline src/main/kotlin/app/morphe/cli/command/PatchCommand.kt]: `apks` file types also exist.

Example apks file to try:
https://github.com/Aefyr/SAI/releases/download/1.0/test.apks

Comment (prateek-who) [reply src/main/kotlin/app/morphe/cli/command/PatchCommand.kt]: Will add this too
